apiVersion: ops.kubedb.com/v1alpha1
kind: ZooKeeperOpsRequest
metadata:
  name: zk-reconfig
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: zk-quickstart
  configuration:
    configSecret:
      name: zk-new-configuration
    restart: auto
