apiVersion: ops.kubedb.com/v1alpha1
kind: RabbitMQOpsRequest
metadata:
  name: reconfigure-rm-cluster
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: rm-cluster
  configuration:
    configSecret:
      name: new-custom-config
    restart: auto
  timeout: 5m
  apply: IfReady