apiVersion: ops.kubedb.com/v1alpha1
kind: RabbitMQOpsRequest
metadata:
  name: reconfigure-rm-cluster
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: rm-cluster
  configuration:
    configuration:
      secretName: new-custom-config
  timeout: 5m
  apply: IfReady