apiVersion: ops.kubedb.com/v1alpha1
kind: PgpoolOpsRequest
metadata:
  name: ppops-reconfigure
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: pp-custom
  configuration:
    secretName: new-custom-config
  timeout: 5m
  apply: IfReady