apiVersion: ops.kubedb.com/v1alpha1
kind: ClickHouseOpsRequest
metadata:
  name: chops-cluster-reconfigure-with-secret
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: clickhouse-prod
  configuration:
    configuration:
      secretName: new-ch-custom-config
  timeout: 10m
  apply: IfReady