apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: mg
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: MongoDB
    namespace: demo
    name: sample-mg-rs
  backends:
    - name: s3-backend
      storageRef:
        namespace: demo
        name: s3-storage-replicaset
      retentionPolicy:
        name: backup-rp
        namespace: demo        
  sessions:
    - name: frequent
      scheduler:
        schedule: "*/3 * * * *"
      repositories:
        - name: s3-repo
          backend: s3-backend
          directory: /replicaset
          encryptionSecret:
           name: encry-secret
           namespace: demo
      addon:
        name: mongodb-addon
        tasks:
          - name: LogicalBackup