apiVersion: kubedb.com/v1alpha2
kind: Pgpool
metadata:
  name: pp-init-config
  namespace: demo
spec:
  version: "4.4.5"
  replicas: 1
  postgresRef:
    name: ha-postgres
    namespace: demo
  configuration:
    inline:
      pgpool.conf: |
        num_init_children=6
        max_pool=65
        child_life_time=400
  deletionPolicy: WipeOut