apiVersion: kubedb.com/v1alpha2
kind: PerconaXtraDB
metadata:
  name: builtin-prom-md
  namespace: demo
spec:
  version: "8.0.26"
  terminationPolicy: WipeOut
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/builtin