apiVersion: ops.kubedb.com/v1alpha1
kind: PostgresOpsRequest
metadata:
  name: pgops-reconfigure-config
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: ha-postgres
  configuration:
    configuration:
      secretName: new-pg-configuration
