apiVersion: kubedb.com/v1alpha2
kind: MariaDB
metadata:
  name: builtin-prom-md
  namespace: demo
spec:
  version: "10.5.8"
  terminationPolicy: WipeOut
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/builtin